// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.audit-log@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const AUDIT_LOG_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const AUDIT_LOG_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_audit_log { () => { "{\"capability_id\":\"lenso.audit-log@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"append_event\",\"get_event\",\"list_events\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_audit_log_client { () => { "{\"capability_id\":\"lenso.audit-log@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_audit_log_client { () => { "{\"capability_id\":\"lenso.audit-log@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const APPEND_EVENT_OPERATION: &str = "append_event";
pub const GET_EVENT_OPERATION: &str = "get_event";
pub const LIST_EVENTS_OPERATION: &str = "list_events";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventRequest {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: String,
    #[serde(rename = "actor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor: AppendEventRequestActor,
    #[serde(rename = "event_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_name: String,
    #[serde(rename = "metadata")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: AppendEventRequestOutcome,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_context")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_context: Option<AppendEventRequestRequestContext>,
    #[serde(rename = "resource")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource: Option<AppendEventRequestResource>,
    #[serde(rename = "scope")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope: Option<AppendEventRequestScope>,
    #[serde(rename = "severity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub severity: AppendEventRequestSeverity,
}

impl fmt::Debug for AppendEventRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AppendEventRequest")
            .field("action", &self.action)
            .field("actor", &self.actor)
            .field("event_name", &self.event_name)
            .field("metadata", &"<redacted>")
            .field("occurred_at", &self.occurred_at)
            .field("outcome", &self.outcome)
            .field("reason", &self.reason)
            .field("request_context", &self.request_context)
            .field("resource", &self.resource)
            .field("scope", &self.scope)
            .field("severity", &self.severity)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventRequestActor {
    #[serde(rename = "display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: Option<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AppendEventRequestOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "denied")]
    Denied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventRequestRequestContext {
    #[serde(rename = "causation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub causation_id: Option<String>,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: Option<String>,
    #[serde(rename = "story_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub story_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventRequestResource {
    #[serde(rename = "display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventRequestScope {
    #[serde(rename = "display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display: Option<String>,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub module: Option<String>,
    #[serde(rename = "scope_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_type: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AppendEventRequestSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventResponse {
    #[serde(rename = "event")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event: AppendEventResponseEvent,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendEventResponseEvent {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: String,
    #[serde(rename = "actor_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_display: Option<String>,
    #[serde(rename = "actor_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_id: Option<String>,
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "causation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub causation_id: Option<String>,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "event_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_name: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "metadata")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: AppendEventResponseEventOutcome,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: Option<String>,
    #[serde(rename = "resource_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_display: Option<String>,
    #[serde(rename = "resource_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_id: Option<String>,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: Option<String>,
    #[serde(rename = "scope_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_display: Option<String>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: Option<String>,
    #[serde(rename = "scope_module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_module: Option<String>,
    #[serde(rename = "scope_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_type: Option<String>,
    #[serde(rename = "severity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub severity: AppendEventResponseEventSeverity,
    #[serde(rename = "source_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_instance: String,
    #[serde(rename = "story_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub story_id: Option<String>,
}

impl fmt::Debug for AppendEventResponseEvent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AppendEventResponseEvent")
            .field("action", &self.action)
            .field("actor_display", &self.actor_display)
            .field("actor_id", &self.actor_id)
            .field("actor_kind", &self.actor_kind)
            .field("causation_id", &self.causation_id)
            .field("correlation_id", &self.correlation_id)
            .field("created_at", &self.created_at)
            .field("event_name", &self.event_name)
            .field("id", &self.id)
            .field("metadata", &"<redacted>")
            .field("occurred_at", &self.occurred_at)
            .field("outcome", &self.outcome)
            .field("reason", &self.reason)
            .field("request_id", &self.request_id)
            .field("resource_display", &self.resource_display)
            .field("resource_id", &self.resource_id)
            .field("resource_type", &self.resource_type)
            .field("scope_display", &self.scope_display)
            .field("scope_id", &self.scope_id)
            .field("scope_module", &self.scope_module)
            .field("scope_type", &self.scope_type)
            .field("severity", &self.severity)
            .field("source_instance", &self.source_instance)
            .field("story_id", &self.story_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AppendEventResponseEventOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "denied")]
    Denied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AppendEventResponseEventSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppendEventError {
    InvalidEvent,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetEventRequest {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetEventResponse {
    #[serde(rename = "event")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event: GetEventResponseEvent,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetEventResponseEvent {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: String,
    #[serde(rename = "actor_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_display: Option<String>,
    #[serde(rename = "actor_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_id: Option<String>,
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "causation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub causation_id: Option<String>,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "event_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_name: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "metadata")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: GetEventResponseEventOutcome,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: Option<String>,
    #[serde(rename = "resource_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_display: Option<String>,
    #[serde(rename = "resource_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_id: Option<String>,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: Option<String>,
    #[serde(rename = "scope_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_display: Option<String>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: Option<String>,
    #[serde(rename = "scope_module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_module: Option<String>,
    #[serde(rename = "scope_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_type: Option<String>,
    #[serde(rename = "severity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub severity: GetEventResponseEventSeverity,
    #[serde(rename = "source_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_instance: String,
    #[serde(rename = "story_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub story_id: Option<String>,
}

impl fmt::Debug for GetEventResponseEvent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("GetEventResponseEvent")
            .field("action", &self.action)
            .field("actor_display", &self.actor_display)
            .field("actor_id", &self.actor_id)
            .field("actor_kind", &self.actor_kind)
            .field("causation_id", &self.causation_id)
            .field("correlation_id", &self.correlation_id)
            .field("created_at", &self.created_at)
            .field("event_name", &self.event_name)
            .field("id", &self.id)
            .field("metadata", &"<redacted>")
            .field("occurred_at", &self.occurred_at)
            .field("outcome", &self.outcome)
            .field("reason", &self.reason)
            .field("request_id", &self.request_id)
            .field("resource_display", &self.resource_display)
            .field("resource_id", &self.resource_id)
            .field("resource_type", &self.resource_type)
            .field("scope_display", &self.scope_display)
            .field("scope_id", &self.scope_id)
            .field("scope_module", &self.scope_module)
            .field("scope_type", &self.scope_type)
            .field("severity", &self.severity)
            .field("source_instance", &self.source_instance)
            .field("story_id", &self.story_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetEventResponseEventOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "denied")]
    Denied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetEventResponseEventSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetEventError {
    InvalidId,
    NotFound,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListEventsRequest {
    #[serde(rename = "actor_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<String>,
    #[serde(rename = "actor_kind")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_kind: Option<String>,
    #[serde(rename = "correlation_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<ListEventsRequestCursor>,
    #[serde(rename = "event_name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "occurred_after")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurred_after: Option<Timestamp>,
    #[serde(rename = "occurred_before")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurred_before: Option<Timestamp>,
    #[serde(rename = "outcome")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outcome: Option<ListEventsRequestOutcome>,
    #[serde(rename = "resource_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<String>,
    #[serde(rename = "resource_type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    #[serde(rename = "scope_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_id: Option<String>,
    #[serde(rename = "scope_module")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_module: Option<String>,
    #[serde(rename = "scope_type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_type: Option<String>,
    #[serde(rename = "severity")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub severity: Option<ListEventsRequestSeverity>,
    #[serde(rename = "source_instance")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_instance: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListEventsRequestCursor {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListEventsRequestOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "denied")]
    Denied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListEventsRequestSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListEventsResponse {
    #[serde(rename = "events")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub events: Vec<ListEventsResponseEventsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<ListEventsResponseNextCursor>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListEventsResponseEventsItem {
    #[serde(rename = "action")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action: String,
    #[serde(rename = "actor_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_display: Option<String>,
    #[serde(rename = "actor_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_id: Option<String>,
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "causation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub causation_id: Option<String>,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "event_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_name: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "metadata")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: ListEventsResponseEventsItemOutcome,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: Option<String>,
    #[serde(rename = "resource_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_display: Option<String>,
    #[serde(rename = "resource_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_id: Option<String>,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: Option<String>,
    #[serde(rename = "scope_display")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_display: Option<String>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: Option<String>,
    #[serde(rename = "scope_module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_module: Option<String>,
    #[serde(rename = "scope_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_type: Option<String>,
    #[serde(rename = "severity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub severity: ListEventsResponseEventsItemSeverity,
    #[serde(rename = "source_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_instance: String,
    #[serde(rename = "story_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub story_id: Option<String>,
}

impl fmt::Debug for ListEventsResponseEventsItem {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ListEventsResponseEventsItem")
            .field("action", &self.action)
            .field("actor_display", &self.actor_display)
            .field("actor_id", &self.actor_id)
            .field("actor_kind", &self.actor_kind)
            .field("causation_id", &self.causation_id)
            .field("correlation_id", &self.correlation_id)
            .field("created_at", &self.created_at)
            .field("event_name", &self.event_name)
            .field("id", &self.id)
            .field("metadata", &"<redacted>")
            .field("occurred_at", &self.occurred_at)
            .field("outcome", &self.outcome)
            .field("reason", &self.reason)
            .field("request_id", &self.request_id)
            .field("resource_display", &self.resource_display)
            .field("resource_id", &self.resource_id)
            .field("resource_type", &self.resource_type)
            .field("scope_display", &self.scope_display)
            .field("scope_id", &self.scope_id)
            .field("scope_module", &self.scope_module)
            .field("scope_type", &self.scope_type)
            .field("severity", &self.severity)
            .field("source_instance", &self.source_instance)
            .field("story_id", &self.story_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListEventsResponseEventsItemOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "denied")]
    Denied,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListEventsResponseEventsItemSeverity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "critical")]
    Critical,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListEventsResponseNextCursor {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListEventsError {
    InvalidQuery,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct AuditLogAppendEvent;
impl RequestCapability for AuditLogAppendEvent {
    type Request = AppendEventRequest;
    type Response = AppendEventResponse;
    type DomainError = AppendEventError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != APPEND_EVENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AuditLogRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).append_event(context, request)
    }
}

#[derive(Debug)]
pub struct AuditLogGetEvent;
impl RequestCapability for AuditLogGetEvent {
    type Request = GetEventRequest;
    type Response = GetEventResponse;
    type DomainError = GetEventError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_EVENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AuditLogRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_event(context, request)
    }
}

#[derive(Debug)]
pub struct AuditLogListEvents;
impl RequestCapability for AuditLogListEvents {
    type Request = ListEventsRequest;
    type Response = ListEventsResponse;
    type DomainError = ListEventsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_EVENTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<AuditLogRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_events(context, request)
    }
}

impl serde::Serialize for AppendEventError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AppendEventError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_event" => Ok(Self::InvalidEvent),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetEventError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidId => serializer.serialize_str("invalid_id"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetEventError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_id" => Ok(Self::InvalidId),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListEventsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListEventsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_query" => Ok(Self::InvalidQuery),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_append_event_request(value: &AppendEventRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_event_request(wire: &str) -> Result<AppendEventRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_event_response(value: &AppendEventResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_event_response(wire: &str) -> Result<AppendEventResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_event_error(value: &AppendEventError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_event_error(wire: &str) -> Result<AppendEventError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_event_request(value: &GetEventRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_event_request(wire: &str) -> Result<GetEventRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_event_response(value: &GetEventResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_event_response(wire: &str) -> Result<GetEventResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_event_error(value: &GetEventError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_event_error(wire: &str) -> Result<GetEventError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_events_request(value: &ListEventsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_events_request(wire: &str) -> Result<ListEventsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_events_response(value: &ListEventsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_events_response(wire: &str) -> Result<ListEventsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_events_error(value: &ListEventsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_events_error(wire: &str) -> Result<ListEventsError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoAuditLogAppendEventResult {
    fn __lenso_into_result(self) -> Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure>;
}
impl __LensoIntoAuditLogAppendEventResult for Result<AppendEventResponse, AppendEventError> {
    fn __lenso_into_result(self) -> Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAuditLogAppendEventResult for Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure> { self }
}
impl __LensoIntoAuditLogAppendEventResult for Result<AppendEventResponse, lenso_plugin_authoring::PluginError<AppendEventError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAuditLogAppendEventResult for Result<AppendEventResponse, AuditLogAppendEventInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AppendEventResponse, AppendEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AuditLogAppendEventInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AuditLogAppendEventInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAuditLogGetEventResult {
    fn __lenso_into_result(self) -> Result<Result<GetEventResponse, GetEventError>, RuntimeFailure>;
}
impl __LensoIntoAuditLogGetEventResult for Result<GetEventResponse, GetEventError> {
    fn __lenso_into_result(self) -> Result<Result<GetEventResponse, GetEventError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAuditLogGetEventResult for Result<Result<GetEventResponse, GetEventError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetEventResponse, GetEventError>, RuntimeFailure> { self }
}
impl __LensoIntoAuditLogGetEventResult for Result<GetEventResponse, lenso_plugin_authoring::PluginError<GetEventError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetEventResponse, GetEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAuditLogGetEventResult for Result<GetEventResponse, AuditLogGetEventInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetEventResponse, GetEventError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AuditLogGetEventInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AuditLogGetEventInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoAuditLogListEventsResult {
    fn __lenso_into_result(self) -> Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure>;
}
impl __LensoIntoAuditLogListEventsResult for Result<ListEventsResponse, ListEventsError> {
    fn __lenso_into_result(self) -> Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoAuditLogListEventsResult for Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure> { self }
}
impl __LensoIntoAuditLogListEventsResult for Result<ListEventsResponse, lenso_plugin_authoring::PluginError<ListEventsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoAuditLogListEventsResult for Result<ListEventsResponse, AuditLogListEventsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListEventsResponse, ListEventsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(AuditLogListEventsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(AuditLogListEventsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait AuditLogProvider: fmt::Debug + 'static {
    fn append_event(&self, context: InvocationContext, request: AppendEventRequest) -> NativeRequestFuture<AuditLogAppendEvent>;
    fn get_event(&self, context: InvocationContext, request: GetEventRequest) -> NativeRequestFuture<AuditLogGetEvent>;
    fn list_events(&self, context: InvocationContext, request: ListEventsRequest) -> NativeRequestFuture<AuditLogListEvents>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_audit_log {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportAuditLog;
        impl $crate::AuditLogProvider for $plugin {
        fn append_event(&self, context: __LensoNativeSupportAuditLog::InvocationContext, request: $crate::AppendEventRequest) -> __LensoNativeSupportAuditLog::NativeRequestFuture<$crate::AuditLogAppendEvent> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::append_event(&plugin, context, request).await;
                $crate::__LensoIntoAuditLogAppendEventResult::__lenso_into_result(result)
            })
        }
        fn get_event(&self, context: __LensoNativeSupportAuditLog::InvocationContext, request: $crate::GetEventRequest) -> __LensoNativeSupportAuditLog::NativeRequestFuture<$crate::AuditLogGetEvent> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_event(&plugin, context, request).await;
                $crate::__LensoIntoAuditLogGetEventResult::__lenso_into_result(result)
            })
        }
        fn list_events(&self, context: __LensoNativeSupportAuditLog::InvocationContext, request: $crate::ListEventsRequest) -> __LensoNativeSupportAuditLog::NativeRequestFuture<$crate::AuditLogListEvents> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_events(&plugin, context, request).await;
                $crate::__LensoIntoAuditLogListEventsResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct AuditLogRequestEndpoint { provider: Rc<dyn AuditLogProvider> }

#[derive(Debug)]
pub struct AuditLogEndpoint<P: AuditLogProvider> { provider: Rc<P>, request_endpoint: AuditLogRequestEndpoint }
impl<P: AuditLogProvider> AuditLogEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn AuditLogProvider> = provider.clone();
        Self { provider, request_endpoint: AuditLogRequestEndpoint { provider: request_provider } }
    }
}

impl<P: AuditLogProvider> NativeRequestEndpoint for AuditLogEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        APPEND_EVENT_OPERATION,
        GET_EVENT_OPERATION,
        LIST_EVENTS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            APPEND_EVENT_OPERATION => {
                let Ok(request) = request.downcast::<AppendEventRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).append_event(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_EVENT_OPERATION => {
                let Ok(request) = request.downcast::<GetEventRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_event(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_EVENTS_OPERATION => {
                let Ok(request) = request.downcast::<ListEventsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_events(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_audit_log {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::AuditLogEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_audit_log {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_audit_log!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct AuditLogClient {
    append_event: NativeRequestHandle<AuditLogAppendEvent>,
    get_event: NativeRequestHandle<AuditLogGetEvent>,
    list_events: NativeRequestHandle<AuditLogListEvents>,
}
impl AuditLogClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn append_event(&self, request: AppendEventRequest) -> Result<AppendEventResponse, AuditLogAppendEventInvocationError> {
        self.append_event.invoke(APPEND_EVENT_OPERATION, request).await
            .map_err(AuditLogAppendEventInvocationError::Runtime)?
            .map_err(AuditLogAppendEventInvocationError::Domain)
    }

    pub async fn append_event_with_context(&self, context: InvocationContext, request: AppendEventRequest) -> Result<AppendEventResponse, AuditLogAppendEventInvocationError> {
        self.append_event.invoke_with_context(APPEND_EVENT_OPERATION, context, request).await
            .map_err(AuditLogAppendEventInvocationError::Runtime)?
            .map_err(AuditLogAppendEventInvocationError::Domain)
    }

    pub async fn get_event(&self, request: GetEventRequest) -> Result<GetEventResponse, AuditLogGetEventInvocationError> {
        self.get_event.invoke(GET_EVENT_OPERATION, request).await
            .map_err(AuditLogGetEventInvocationError::Runtime)?
            .map_err(AuditLogGetEventInvocationError::Domain)
    }

    pub async fn get_event_with_context(&self, context: InvocationContext, request: GetEventRequest) -> Result<GetEventResponse, AuditLogGetEventInvocationError> {
        self.get_event.invoke_with_context(GET_EVENT_OPERATION, context, request).await
            .map_err(AuditLogGetEventInvocationError::Runtime)?
            .map_err(AuditLogGetEventInvocationError::Domain)
    }

    pub async fn list_events(&self, request: ListEventsRequest) -> Result<ListEventsResponse, AuditLogListEventsInvocationError> {
        self.list_events.invoke(LIST_EVENTS_OPERATION, request).await
            .map_err(AuditLogListEventsInvocationError::Runtime)?
            .map_err(AuditLogListEventsInvocationError::Domain)
    }

    pub async fn list_events_with_context(&self, context: InvocationContext, request: ListEventsRequest) -> Result<ListEventsResponse, AuditLogListEventsInvocationError> {
        self.list_events.invoke_with_context(LIST_EVENTS_OPERATION, context, request).await
            .map_err(AuditLogListEventsInvocationError::Runtime)?
            .map_err(AuditLogListEventsInvocationError::Domain)
    }
}

impl CapabilityClient for AuditLogClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            append_event: dependencies.one::<AuditLogAppendEvent>()?,
            get_event: dependencies.one::<AuditLogGetEvent>()?,
            list_events: dependencies.one::<AuditLogListEvents>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for AuditLogClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    append_event: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AuditLogAppendEvent>()?,
                    get_event: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AuditLogGetEvent>()?,
                    list_events: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<AuditLogListEvents>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum AuditLogAppendEventInvocationError {
    Domain(AppendEventError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AuditLogGetEventInvocationError {
    Domain(GetEventError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum AuditLogListEventsInvocationError {
    Domain(ListEventsError),
    Runtime(RuntimeFailure),
}
